### PR TITLE
Upgrade to Django 2.0 (breaks <2.0)

### PR DESCRIPTION
**Pull request by LaundroMat**
Updated the code to work with Django 2.0 and higher. All  tests pass on my local machine, but I haven't used it in a Django app yet (will try soon).

### CODE REVIEW

**Comment by danfairs** [comment]
Hi there! Many thanks for working on this. I'd be happy to merge support for Django 2.0+ and drop support for older versions, as long as that's accompanied by a major version bump.

Looks like some of the Travis CI tests are failing, would be great to take a look at those.

**Comment by LaundroMat** [comment]
Very happy I can help!
I did have quick look and the tests are failing because they don't use Django 2.0 . But tbh, this is my first PR ever, and I have no clue of how to make more CI test or adapt them.

**Comment by LaundroMat** [comment]
The code is now Django 2.0+ compliant, but breaks with earlier versions of Django.

It seems most if not all of the breaking code can be made backwards compatible again (e.g. checking whether `is_authenticated` is a method or a property), but I wonder if that's what you'd like (as you said you'd prefer a version bump and drop support for <2.0).

**Comment by LaundroMat** [comment]
Sorry for these silly commits; I'm trying to find out why the tests fail with Django 2.1

I'll look into it further when I have the time...

**Comment by LaundroMat** [comment]
Well that went quick :)

**Comment by glowka** [comment]
:+1: 

I had reported #61 and now found this which solves the issue. It would be great to merge this and release!

**Comment by danfairs** [comment]
OK, it's been a little while (sorry, everyone, sorry...) but I merged this and uploaded to PyPI as version 2.0.0. Thanks @LaundroMat!

**Comment by LaundroMat** [comment]
That's my first accepted PR ever, thanks 😊

**Pull request merged**
